### Get all radios
GET https://cse341-project2-rcz6.onrender.com/radios HTTP/1.1

### Get all repeaters
GET https://cse341-project2-rcz6.onrender.com/repeaters HTTP/1.1

### Get radios by Id
GET https://cse341-project2-rcz6.onrender.com/radios/65f61a798a0eb4614c1f0f7f HTTP/1.1

### Get repeaters by Id
GET https://cse341-project2-rcz6.onrender.com/repeaters/65f61d28ecf021028e2d09e5 HTTP/1.1

### Create a radios
POST https://cse341-project2-rcz6.onrender.com/radios HTTP/1.1
Content-Type: application/json

{
    "make": "Icom",
    "model": "ID-52A",
    "partNumber": "ICO-ID-52A",
    "bands": "2M/70cm",
    "watts": "5",
    "mode": "D-STAR",
    "price": "599.95"
}

### Create a repeaters
POST https://cse341-project2-rcz6.onrender.com/repeaters HTTP/1.1
Content-Type: application/json

{
    "location": "Post Falls",
    "county": "Kootenai",
    "callSign": "K7ID",
    "frequency": "146.98",
    "toneUp": "127.3",
    "toneDown": "127.3",
    "modes": "FM",
    "updated": "3/21/2024",
    "status": "online"
}

### Put radios (Change a radios)
PUT https://cse341-project2-rcz6.onrender.com/radios/65f6255f433c69d5913e8142 HTTP/1.1
Content-Type: application/json

{
    "make": "Icom",
    "model": "ID-52A",
    "partNumber": "ICO-ID-52A",
    "bands": "2M/70cm",
    "watts": "5",
    "mode": "D-STAR",
    "price": "624.90"
}

### Put repeaters (Change a repeaters)
PUT https://cse341-project2-rcz6.onrender.com/repeaters/65f625ef433c69d5913e8143 HTTP/1.1
content-type: application/json

{
    "location": "Post Falls",
    "county": "Kootenai",
    "callSign": "K7ID",
    "frequency": "146.98",
    "toneUp": "127.3",
    "toneDown": "127.3",
    "modes": "FM",
    "updated": "3/21/2024",
    "status": "online"
}
### Delete radios
DELETE https://cse341-project2-rcz6.onrender.com/radios/65f61a798a0eb4614c1f0f7f HTTP/1.1

### Delete repeaters
DELETE https://cse341-project2-rcz6.onrender.com/repeaters/65f6253f433c69d5913e8141 HTTP/1.1

### Get all radios
GET http://localhost:3000/radios

### Get all repeaters
GET http://localhost:3000/repeaters

### Get radios by ID
GET http://localhost:3000/radios/65f61a798a0eb4614c1f0f7f

### Get repeaters by ID
GET http://localhost:3000/repeaters/65f61d28ecf021028e2d09e5

###Create radios 
POST http://localhost:3000/radios HTTP/1.1 
content-type: application/json

{
    "make": "Icom",
    "model": "ID-52A",
    "partNumber": "ICO-ID-52A",
    "bands": "2M/70cm",
    "watts": "5",
    "mode": "D-STAR",
    "price": "599.95"
}

###Create repeaters
POST http://localhost:3000/repeaters HTTP/1.1 
content-type: application/json

{
    "location": "Post Falls",
    "county": "Kootenai",
    "callSign": "K7ID",
    "frequency": "146.98",
    "toneUp": "127.3",
    "toneDown": "127.3",
    "modes": "FM",
    "updated": "3/21/2024",
    "status": "online"
}

### PUT radios 
PUT http://localhost:3000/radios/65f625ef433c69d5913e8143 HTTP/1.1 
content-type: application/json

{
    "make": "Icom",
    "model": "ID-52A",
    "partNumber": "ICO-ID-52A",
    "bands": "2M/70cm",
    "watts": "5",
    "mode": "D-STAR",
    "price": "500.00"
}

### PUT repeaters
PUT http://localhost:3000/repeaters/65f625ef433c69d5913e8143 HTTP/1.1 
content-type: application/json

{
    "location": "Post Falls",
    "county": "Kootenai",
    "callSign": "K7ID",
    "frequency": "146.98",
    "toneUp": "127.3",
    "toneDown": "127.3",
    "modes": "FM",
    "updated": "3/21/2024",
    "status": "offline"
}

### DELETE radios 
DELETE http://localhost:3000/radios/65f62c00c49c164464309675 HTTP/1.1

### DELETE repeaters
DELETE http://localhost:3000/repeaters/65f61d28ecf021028e2d09e5 HTTP/1.1


